apiVersion: v1
appVersion: V1.0
description: 'Naast deze JSON rest API is er ook een [graphql](/graphql) interface beschikbaar.'
name: ce
version: 0.1.0
home: ce.zaakonline.nl
icon: ce.zaakonline.nl
sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
keywords:
    - commonground
    - haven
    - nlx
    - component
maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.1.1
      condition: postgresql.enabled
